// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Person struct {
	Name     string    `json:"name"`
	Parents  []*string `json:"parents"`
	Children []*string `json:"children"`
}
